const CFG=window.PRO4A_CONFIG;let session=null,records=[],users=[],history=[],currentPage=1,pageSize=12,charts={},recordModal,viewModal,userModal;
const UNITS=["Cavite PPO","Laguna PPO","Rizal PPO","Batangas PPO","Quezon PPO","RHQ"];
const WORKFLOW=["Incident Recorded","Requirements Submitted","For Validation","RHE Processing","NAPOLCOM Processing","PSMBFI Processing","Financial Assistance Released","Completed"];
const CHECKLIST=["Incident Report","Spot Report","Medical Certificate","Death Certificate","Investigation Report","Endorsement","RHE Requirements","NAPOLCOM Requirements","PSMBFI Requirements","Other Supporting Documents"];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let activeRequests = 0;  function busy(isLoading) {   const loadingElement = document.querySelector("#loading");   if (!loadingElement) return;    if (isLoading) {     activeRequests++;   } else {     activeRequests = Math.max(0, activeRequests - 1);   }    loadingElement.classList.toggle("d-none", activeRequests === 0); }
function toast(m){const d=document.createElement("div");d.className="app-toast";d.textContent=m;$("#toastBox").appendChild(d);setTimeout(()=>d.remove(),3500)}
async function api(action,payload={}){if(!CFG.API_URL||CFG.API_URL.includes("PASTE_"))throw new Error("Paste your existing Apps Script /exec URL in config.js.");const data=new URLSearchParams();data.append("data",JSON.stringify({action,token:session?.token||"",...payload}));busy(true);try{const r=await fetch(CFG.API_URL,{method:"POST",body:data,redirect:"follow"});const out=await r.json();if(!out.ok)throw new Error(out.error||"Request failed.");return out}finally{busy(false)}}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function fmtDate(v){if(!v)return"—";const d=new Date(v);return isNaN(d)?String(v):d.toLocaleDateString("en-PH",{year:"numeric",month:"short",day:"2-digit"})}
function statusChip(s){return `<span class="status-chip status-${String(s).toLowerCase().replaceAll(" ","-")}">${esc(s)}</span>`}
function typeChip(s){return `<span class="type-chip type-${String(s).toLowerCase()}">${esc(s)}</span>`}
function checklistObj(v){try{return typeof v==="object"&&v?v:JSON.parse(v||"{}")}catch{return{}}}
function workflow(stage){const idx=Math.max(0,WORKFLOW.indexOf(stage));return `<div class="workflow-track">${WORKFLOW.map((x,i)=>`<div class="workflow-node ${i<idx?"done":i===idx?"current":""}"><div class="workflow-icon">${i<idx?'<i class="bi bi-check-lg"></i>':i+1}</div><span>${x}</span></div>`).join("")}</div>`}
$$(".auth-tab").forEach(b=>b.onclick=()=>{$$(".auth-tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("#loginForm").classList.toggle("d-none",b.dataset.tab!=="login");$("#signupForm").classList.toggle("d-none",b.dataset.tab!=="signup")});
$$(".toggle-password").forEach(b=>b.onclick=()=>{const i=$("#"+b.dataset.target);i.type=i.type==="password"?"text":"password";b.innerHTML=`<i class="bi bi-${i.type==="password"?"eye":"eye-slash"}"></i>`});
$("#loginForm").onsubmit=async e=>{e.preventDefault();try{const d=await api("login",{username:$("#loginUsername").value.trim(),password:$("#loginPassword").value});session=d.session;localStorage.setItem("pro4a_session",JSON.stringify(session));await openApp()}catch(err){toast(err.message)}};
$("#signupForm").onsubmit=async e=>{e.preventDefault();try{await api("signup",{name:$("#signupName").value.trim(),unit:$("#signupUnit").value,username:$("#signupUsername").value.trim(),password:$("#signupPassword").value});e.target.reset();toast("Registration submitted for Administrator approval.")}catch(err){toast(err.message)}};
$("#logoutBtn").onclick=async()=>{try{await api("logout")}catch{}localStorage.removeItem("pro4a_session");location.reload()};
$("#menuBtn").onclick=()=>$("#sidebar").classList.add("open");$("#closeMenu").onclick=()=>$("#sidebar").classList.remove("open");
$("#themeBtn").onclick=()=>{document.body.classList.toggle("dark");localStorage.setItem("pro4a_theme",document.body.classList.contains("dark")?"dark":"light");updateThemeIcon()};
function updateThemeIcon(){$("#themeBtn").innerHTML=`<i class="bi bi-${document.body.classList.contains("dark")?"sun":"moon-stars"}"></i>`}
$$(".nav-btn").forEach(b=>b.onclick=()=>showPage(b.dataset.page));$$("[data-page-jump]").forEach(b=>b.onclick=()=>showPage(b.dataset.pageJump));
function showPage(p){if(p==="users"&&session.role!=="admin")return;$$(".page").forEach(x=>x.classList.remove("active"));$("#"+p+"Page").classList.add("active");$$(".nav-btn").forEach(x=>x.classList.toggle("active",x.dataset.page===p));const titles={dashboard:["Executive Dashboard","Real-time claims overview and accountable actions"],records:["KIPO/WIPO Records","Personnel registry, workflow, and documentary monitoring"],users:["User Management","Approval, access status, unit assignment, and password reset"],history:["Activity History","Accountable actions by authorized users"],reports:["Reports","Export and print monitoring summaries"],profile:["My Profile","Account information and password management"]};$("#pageTitle").textContent=titles[p][0];$("#pageSubtitle").textContent=titles[p][1];$("#sidebar").classList.remove("open");if(p==="dashboard")loadDashboard();if(p==="records")loadRecords();if(p==="users")loadUsers();if(p==="history")loadHistory()}
async function openApp(){try{const d=await api("validateSession");session=d.session;localStorage.setItem("pro4a_session",JSON.stringify(session))}catch(e){localStorage.removeItem("pro4a_session");$("#authView").classList.remove("d-none");$("#appView").classList.add("d-none");return}$("#authView").classList.add("d-none");$("#appView").classList.remove("d-none");$("#sideName").textContent=session.name;$("#sideUnit").textContent=session.unit;$("#roleBadge").textContent=session.role==="admin"?"Administrator":"Unit User";$("#welcomeText").textContent=`Welcome, ${session.name}`;$$(".admin-only").forEach(x=>x.classList.toggle("d-none",session.role!=="admin"));$("#profileName").value=session.name;$("#profileUnit").value=session.unit;recordModal=new bootstrap.Modal("#recordModal");viewModal=new bootstrap.Modal("#viewModal");userModal=new bootstrap.Modal("#userModal");await refreshBadge();showPage("dashboard")}
async function refreshBadge(){if(session.role!=="admin")return;try{const d=await api("pendingUserCount");$("#pendingBadge").textContent=d.count;$("#pendingBadge").classList.toggle("d-none",!d.count)}catch{}}
async function loadDashboard(){try{const d=await api("dashboardV2");const m=d.metrics;["Total","Kipo","Wipo","Pending","Completed"].forEach(k=>$("#m"+k).textContent=m[k.toLowerCase()]);drawChart("unitChart","bar",Object.keys(d.byUnit),Object.values(d.byUnit),"Claims");drawChart("typeChart","doughnut",["KIPO","WIPO"],[m.kipo,m.wipo],"Claims");drawChart("workflowChart","bar",Object.keys(d.byWorkflow),Object.values(d.byWorkflow),"Claims",{indexAxis:"y"});$("#recentActivity").innerHTML=d.recent.map(x=>`<div class="activity-item"><div class="activity-dot"><i class="bi bi-clock-history"></i></div><div><b>${esc(x.action)}</b><p>${esc(x.details)}</p><small>${esc(x.dateTime)} • ${esc(x.user)}</small></div></div>`).join("")||"<p class='text-secondary'>No recent activity.</p>"}catch(e){toast(e.message)}}
function drawChart(id,type,labels,data,label,extra={}){if(charts[id])charts[id].destroy();charts[id]=new Chart($("#"+id),{type,data:{labels,datasets:[{label,data}]},options:{responsive:true,maintainAspectRatio:true,plugins:{legend:{display:type==="doughnut"}},...extra}})}
async function loadRecords(){try{const d=await api("listRecords");records=d.records;currentPage=1;renderRecords()}catch(e){toast(e.message)}}
function filtered(){const q=$("#searchBox").value.toLowerCase(),t=$("#typeFilter").value,y=$("#yearFilter").value,s=$("#statusFilter").value;return records.filter(r=>(!q||JSON.stringify(r).toLowerCase().includes(q))&&(!t||r.type===t)&&(!y||String(r.year)===y)&&(!s||r.status===s))}
function renderRecords(){const all=filtered(),pages=Math.max(1,Math.ceil(all.length/pageSize));currentPage=Math.min(currentPage,pages);const list=all.slice((currentPage-1)*pageSize,currentPage*pageSize);$("#recordCount").textContent=`${all.length} record${all.length===1?"":"s"}`;$("#recordsBody").innerHTML=list.map(r=>`<tr><td><span class="claim-id">${esc(r.claimId)}</span><br><small>${esc(r.year)}</small></td><td>${typeChip(r.type)}</td><td><strong>${esc(r.rankName)}</strong><br><small>${esc(r.badgeNumber||"")}</small></td><td>${esc(r.unit)}<br><small>${esc(r.office||"")}</small></td><td><span class="stage-chip">${esc(r.workflowStage||"Incident Recorded")}</span></td><td>${statusChip(r.status)}</td><td><div class="action-row"><button class="btn btn-sm btn-outline-secondary" onclick="viewRecord('${r.id}')"><i class="bi bi-eye"></i></button><button class="btn btn-sm btn-outline-primary" onclick="editRecord('${r.id}')"><i class="bi bi-pencil"></i></button>${session.role==="admin"?`<button class="btn btn-sm btn-outline-danger" onclick="deleteRecord('${r.id}')"><i class="bi bi-trash"></i></button>`:""}</div></td></tr>`).join("")||`<tr><td colspan="7" class="text-center py-5 text-secondary">No records found.</td></tr>`;$("#pageInfo").textContent=`Page ${currentPage} of ${pages}`;$("#prevPage").disabled=currentPage<=1;$("#nextPage").disabled=currentPage>=pages}
["searchBox","typeFilter","yearFilter","statusFilter"].forEach(id=>$("#"+id).addEventListener(id==="searchBox"?"input":"change",()=>{currentPage=1;renderRecords()}));$("#prevPage").onclick=()=>{currentPage--;renderRecords()};$("#nextPage").onclick=()=>{currentPage++;renderRecords()};$("#refreshBtn").onclick=loadRecords;
$("#addBtn").onclick=()=>openRecord();window.editRecord=id=>openRecord(records.find(r=>r.id===id));
function setWorkflowOptions(selected){$("#workflowStage").innerHTML=WORKFLOW.map(x=>`<option ${x===selected?"selected":""}>${x}</option>`).join("");$("#workflowPreview").innerHTML=workflow(selected)}
$("#workflowStage").onchange=()=>$("#workflowPreview").innerHTML=workflow($("#workflowStage").value);
function renderChecklist(data={}){$("#checklistForm").innerHTML=CHECKLIST.map((x,i)=>`<label class="check-item"><input class="form-check-input me-2 checklist-box" type="checkbox" data-doc="${esc(x)}" ${data[x]?"checked":""}><strong>${esc(x)}</strong></label>`).join("")}
function openRecord(r=null){$("#recordModalTitle").textContent=r?"Edit Personnel Claim":"Add KIPO/WIPO Personnel";$("#recordId").value=r?.id||"";$("#recordType").value=r?.type||"KIPO";$("#recordYear").value=r?.year||2026;$("#recordStatus").value=r?.status||"Pending";$("#recordBadge").value=r?.badgeNumber||"";$("#recordName").value=r?.rankName||"";$("#recordUnit").value=r?.unit||session.unit;$("#recordOffice").value=r?.office||"";$("#recordProvince").value=r?.province||"";$("#recordDate").value=/^\d{4}-\d{2}-\d{2}$/.test(r?.dateIncident||"")?r.dateIncident:"";$("#recordInjury").value=r?.injury||"";$("#recordBenefits").value=r?.benefits||"";$("#recordRemarks").value=r?.remarks||"";$("#recordUnit").disabled=session.role!=="admin";setWorkflowOptions(r?.workflowStage||"Incident Recorded");renderChecklist(checklistObj(r?.checklistJson));recordModal.show()}
$("#recordForm").onsubmit=async e=>{e.preventDefault();const checklist={};$$(".checklist-box").forEach(x=>checklist[x.dataset.doc]=x.checked);const rec={id:$("#recordId").value,type:$("#recordType").value,year:$("#recordYear").value,status:$("#recordStatus").value,badgeNumber:$("#recordBadge").value.trim(),rankName:$("#recordName").value.trim(),unit:session.role==="admin"?$("#recordUnit").value:session.unit,office:$("#recordOffice").value.trim(),province:$("#recordProvince").value.trim(),dateIncident:$("#recordDate").value,injury:$("#recordInjury").value.trim(),workflowStage:$("#workflowStage").value,checklistJson:JSON.stringify(checklist),benefits:$("#recordBenefits").value.trim(),remarks:$("#recordRemarks").value.trim()};try{await api(rec.id?"updateRecordV2":"addRecordV2",{record:rec});recordModal.hide();toast(rec.id?"Record updated successfully.":"New claim record created.");await loadRecords()}catch(err){toast(err.message)}};
window.deleteRecord=async id=>{const r=records.find(x=>x.id===id);if(!confirm(`Delete ${r.claimId} — ${r.rankName}? This is recorded in the audit history.`))return;try{await api("deleteRecord",{id});toast("Record deleted.");loadRecords()}catch(e){toast(e.message)}};
window.viewRecord=id=>{const r=records.find(x=>x.id===id),c=checklistObj(r.checklistJson);$("#viewTitle").textContent=r.rankName;$("#viewClaim").textContent=`${r.claimId} • ${r.type} • CY ${r.year}`;$("#viewBody").innerHTML=`<div class="detail-grid"><div class="detail-box"><label>Unit</label><strong>${esc(r.unit)}</strong></div><div class="detail-box"><label>Office</label><strong>${esc(r.office||"—")}</strong></div><div class="detail-box"><label>Badge Number</label><strong>${esc(r.badgeNumber||"—")}</strong></div><div class="detail-box"><label>Date of Incident</label><strong>${esc(fmtDate(r.dateIncident))}</strong></div><div class="detail-box"><label>Status</label>${statusChip(r.status)}</div><div class="detail-box"><label>Workflow</label><strong>${esc(r.workflowStage||"Incident Recorded")}</strong></div><div class="detail-box detail-full"><label>Nature of Injury / Case</label><strong>${esc(r.injury||"—")}</strong></div><div class="detail-box detail-full"><label>Benefits / Assistance</label><strong>${esc(r.benefits||"—")}</strong></div><div class="detail-box detail-full"><label>Remarks</label><strong>${esc(r.remarks||"—")}</strong></div></div><h6 class="mt-4">Claim Workflow</h6>${workflow(r.workflowStage||"Incident Recorded")}<h6 class="mt-4">Document Checklist</h6><div class="checklist-grid">${CHECKLIST.map(x=>`<div class="check-item"><i class="bi bi-${c[x]?"check-circle-fill text-success":"circle text-secondary"} me-2"></i>${esc(x)}</div>`).join("")}</div>`;viewModal.show()};
async function loadUsers(){try{const d=await api("listUsersV2");users=d.users;$("#usersBody").innerHTML=users.map(u=>`<tr><td><strong>${esc(u.name)}</strong></td><td>${esc(u.username)}</td><td>${esc(u.unit)}</td><td>${statusChip(u.status)}</td><td>${esc(fmtDate(u.createdAt))}</td><td><div class="action-row">${u.status==="Pending"?`<button class="btn btn-sm btn-success" onclick="setUser('${u.id}','Approved')">Approve</button><button class="btn btn-sm btn-danger" onclick="setUser('${u.id}','Rejected')">Reject</button>`:`<button class="btn btn-sm btn-outline-warning" onclick="setUser('${u.id}','${u.status==="Approved"?"Disabled":"Approved"}')">${u.status==="Approved"?"Disable":"Enable"}</button>`}<button class="btn btn-sm btn-outline-primary" onclick="manageUser('${u.id}')"><i class="bi bi-gear"></i></button></div></td></tr>`).join("")||`<tr><td colspan="6">No users.</td></tr>`}catch(e){toast(e.message)}}
window.setUser=async(id,status)=>{try{await api("setUserStatus",{id,status});toast(`User ${status.toLowerCase()}.`);loadUsers();refreshBadge()}catch(e){toast(e.message)}};
window.manageUser=id=>{const u=users.find(x=>x.id===id);$("#userId").value=u.id;$("#manageUserName").value=u.name;$("#manageUserUnit").value=u.unit;$("#tempPassword").value="";userModal.show()};
$("#userForm").onsubmit=async e=>{e.preventDefault();try{await api("updateUserAdmin",{id:$("#userId").value,name:$("#manageUserName").value.trim(),unit:$("#manageUserUnit").value,tempPassword:$("#tempPassword").value});userModal.hide();toast("User account updated.");loadUsers()}catch(err){toast(err.message)}};
async function loadHistory(){try{const d=await api("history");history=d.history;$("#historyBody").innerHTML=history.map(h=>`<tr><td>${esc(h.dateTime)}</td><td><strong>${esc(h.user)}</strong></td><td>${esc(h.unit)}</td><td><span class="stage-chip">${esc(h.action)}</span></td><td>${esc(h.details)}</td></tr>`).join("")||"<tr><td colspan='5'>No activity.</td></tr>"}catch(e){toast(e.message)}}
$("#profileForm").onsubmit=async e=>{e.preventDefault();try{const d=await api("updateProfile",{name:$("#profileName").value.trim(),currentPassword:$("#currentPassword").value,newPassword:$("#newPassword").value});session=d.session;localStorage.setItem("pro4a_session",JSON.stringify(session));$("#sideName").textContent=session.name;$("#currentPassword").value=$("#newPassword").value="";toast("Profile updated.")}catch(e){toast(e.message)}};
function downloadCsv(name,rows){if(!rows.length)return toast("No records to export.");const keys=Object.keys(rows[0]);const csv=[keys.join(","),...rows.map(r=>keys.map(k=>`"${String(r[k]??"").replaceAll('"','""')}"`).join(","))].join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv"}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
$("#exportCsvBtn").onclick=()=>downloadCsv("PRO4A_KIPO_WIPO_Registry.csv",filtered().map(r=>({ClaimID:r.claimId,Type:r.type,Year:r.year,RankName:r.rankName,Unit:r.unit,Office:r.office,Workflow:r.workflowStage,Status:r.status,Benefits:r.benefits,Remarks:r.remarks})));
$$(".report-btn").forEach(b=>b.onclick=()=>{const kind=b.dataset.report;if(kind==="unit"){const m={};records.forEach(r=>m[r.unit]=(m[r.unit]||0)+1);downloadCsv("Claims_By_Unit.csv",Object.entries(m).map(([Unit,Claims])=>({Unit,Claims})))}else if(kind==="year"){const m={};records.forEach(r=>m[r.year]=(m[r.year]||0)+1);downloadCsv("Claims_By_Year.csv",Object.entries(m).map(([Year,Claims])=>({Year,Claims})))}else{const m={};records.forEach(r=>m[r.workflowStage||"Incident Recorded"]=(m[r.workflowStage||"Incident Recorded"]||0)+1);downloadCsv("Claims_By_Workflow.csv",Object.entries(m).map(([Workflow,Claims])=>({Workflow,Claims})))}});$("#printBtn").onclick=()=>{showPage("records");setTimeout(()=>window.print(),300)};
(async()=>{if(localStorage.getItem("pro4a_theme")==="dark")document.body.classList.add("dark");updateThemeIcon();const s=localStorage.getItem("pro4a_session");if(s){session=JSON.parse(s);await openApp()}})();
