const CFG=window.PRO4A_CONFIG;let session=null,records=[],users=[],history=[],unitChart,typeChart,recordModal;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function toast(m){const d=document.createElement("div");d.className="app-toast";d.textContent=m;$("#toastBox").appendChild(d);setTimeout(()=>d.remove(),3200)}
async function api(action,payload={}){if(!CFG.API_URL||CFG.API_URL.includes("PASTE_"))throw new Error("Set the Google Apps Script Web App URL in config.js.");const r=await fetch(CFG.API_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action,token:session?.token||"",...payload})});const data=await r.json();if(!data.ok)throw new Error(data.error||"Request failed");return data}
$$(".auth-tab").forEach(b=>b.onclick=()=>{$$(".auth-tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("#loginForm").classList.toggle("d-none",b.dataset.tab!=="login");$("#signupForm").classList.toggle("d-none",b.dataset.tab!=="signup")});
$("#loginForm").onsubmit=async e=>{e.preventDefault();try{const d=await api("login",{username:$("#loginUsername").value,password:$("#loginPassword").value});session=d.session;localStorage.setItem("pro4a_session",JSON.stringify(session));openApp()}catch(err){toast(err.message)}};
$("#signupForm").onsubmit=async e=>{e.preventDefault();try{await api("signup",{name:$("#signupName").value,unit:$("#signupUnit").value,username:$("#signupUsername").value,password:$("#signupPassword").value});e.target.reset();toast("Registration submitted. Wait for Admin approval.")}catch(err){toast(err.message)}};
$("#logoutBtn").onclick=async()=>{try{await api("logout")}catch(e){}localStorage.removeItem("pro4a_session");location.reload()};
$$(".side-link").forEach(b=>b.onclick=()=>showPage(b.dataset.page));
$("#menuBtn").onclick=()=>$(".sidebar").classList.toggle("open");
function showPage(p){if(["users"].includes(p)&&session.role!=="admin")return;$$(".page").forEach(x=>x.classList.remove("active"));$("#"+p+"Page").classList.add("active");$$(".side-link").forEach(x=>x.classList.toggle("active",x.dataset.page===p));$("#pageTitle").textContent={dashboard:"Dashboard",records:"KIPO/WIPO Records",users:"User Approval",history:"Activity History",profile:"My Profile"}[p];$(".sidebar").classList.remove("open");if(p==="dashboard")loadDashboard();if(p==="records")loadRecords();if(p==="users")loadUsers();if(p==="history")loadHistory()}
async function openApp(){try{const d=await api("validateSession");session=d.session;localStorage.setItem("pro4a_session",JSON.stringify(session))}catch(e){localStorage.removeItem("pro4a_session");return}$("#authView").classList.add("d-none");$("#appView").classList.remove("d-none");$("#loggedUser").textContent=`${session.name} • ${session.unit}`;$("#roleBadge").textContent=session.role.toUpperCase();$$(".admin-only").forEach(x=>x.classList.toggle("d-none",session.role!=="admin"));$("#profileName").value=session.name;$("#profileUnit").value=session.unit;recordModal=new bootstrap.Modal("#recordModal");await refreshBadge();showPage("dashboard")}
async function refreshBadge(){if(session.role!=="admin")return;try{const d=await api("pendingUserCount");$("#pendingBadge").textContent=d.count;$("#pendingBadge").classList.toggle("d-none",!d.count)}catch(e){}}
async function loadRecords(){try{const d=await api("listRecords");records=d.records;renderRecords()}catch(e){toast(e.message)}}
function filtered(){const q=$("#searchBox").value.toLowerCase(),t=$("#typeFilter").value,y=$("#yearFilter").value,s=$("#statusFilter").value;return records.filter(r=>(!q||JSON.stringify(r).toLowerCase().includes(q))&&(!t||r.type===t)&&(!y||String(r.year)===y)&&(!s||r.status===s))}
function tag(s){return `<span class="status s-${String(s).toLowerCase().replaceAll(" ","-")}">${s}</span>`}
function renderRecords(){const list=filtered();$("#recordsBody").innerHTML=list.map(r=>`<tr><td>${r.claimId}</td><td><b>${r.type}</b></td><td>${r.year}</td><td>${r.rankName}</td><td>${r.unit}</td><td>${tag(r.status)}</td><td><div class="mini-actions"><button class="btn btn-outline-primary" onclick="editRecord('${r.id}')">Edit</button>${session.role==="admin"?`<button class="btn btn-outline-danger" onclick="deleteRecord('${r.id}')">Delete</button>`:""}</div></td></tr>`).join("")||`<tr><td colspan="7">No records found.</td></tr>`}
["searchBox","typeFilter","yearFilter","statusFilter"].forEach(id=>$("#"+id).addEventListener(id==="searchBox"?"input":"change",renderRecords));
$("#refreshBtn").onclick=loadRecords;$("#addBtn").onclick=()=>openRecord();
function openRecord(r=null){$("#recordModalTitle").textContent=r?"Edit Personnel":"Add Personnel";$("#recordId").value=r?.id||"";$("#recordType").value=r?.type||"KIPO";$("#recordYear").value=r?.year||2026;$("#recordStatus").value=r?.status||"Pending";$("#recordName").value=r?.rankName||"";$("#recordUnit").value=r?.unit||session.unit;$("#recordDate").value=r?.dateIncident||"";$("#recordInjury").value=r?.injury||"";$("#recordBenefits").value=r?.benefits||"";$("#recordRemarks").value=r?.remarks||"";$("#recordUnit").disabled=session.role!=="admin";recordModal.show()}
window.editRecord=id=>openRecord(records.find(r=>r.id===id));
window.deleteRecord=async id=>{const r=records.find(x=>x.id===id);if(!confirm(`Delete ${r.rankName}?`))return;try{await api("deleteRecord",{id});toast("Record deleted.");loadRecords()}catch(e){toast(e.message)}}
$("#recordForm").onsubmit=async e=>{e.preventDefault();const rec={id:$("#recordId").value,type:$("#recordType").value,year:$("#recordYear").value,status:$("#recordStatus").value,rankName:$("#recordName").value,unit:session.role==="admin"?$("#recordUnit").value:session.unit,dateIncident:$("#recordDate").value,injury:$("#recordInjury").value,benefits:$("#recordBenefits").value,remarks:$("#recordRemarks").value};try{await api(rec.id?"updateRecord":"addRecord",{record:rec});recordModal.hide();toast(rec.id?"Record updated.":"Personnel added.");loadRecords();refreshBadge()}catch(err){toast(err.message)}};
async function loadDashboard(){try{const d=await api("dashboard");const m=d.metrics;$("#mTotal").textContent=m.total;$("#mKipo").textContent=m.kipo;$("#mWipo").textContent=m.wipo;$("#mPending").textContent=m.pending;$("#mCompleted").textContent=m.completed;drawCharts(d.byUnit,m);$("#recentActivity").innerHTML=d.recent.map(x=>`<div class="border-bottom py-2"><b>${x.action}</b> — ${x.details}<br><small class="text-secondary">${x.dateTime} • ${x.user}</small></div>`).join("")||"<span class='text-secondary'>No recent activity.</span>"}catch(e){toast(e.message)}}
function drawCharts(byUnit,m){if(unitChart)unitChart.destroy();if(typeChart)typeChart.destroy();unitChart=new Chart($("#unitChart"),{type:"bar",data:{labels:Object.keys(byUnit),datasets:[{label:"Claims",data:Object.values(byUnit)}]},options:{plugins:{legend:{display:false}},responsive:true}});typeChart=new Chart($("#typeChart"),{type:"doughnut",data:{labels:["KIPO","WIPO"],datasets:[{data:[m.kipo,m.wipo]}]},options:{responsive:true}})}
async function loadUsers(){try{const d=await api("listUsers");users=d.users;$("#usersBody").innerHTML=users.map(u=>`<tr><td>${u.name}</td><td>${u.unit}</td><td>${u.username}</td><td>${u.status}</td><td><div class="mini-actions">${u.status==="Pending"?`<button class="btn btn-success" onclick="approveUser('${u.id}')">Approve</button><button class="btn btn-danger" onclick="rejectUser('${u.id}')">Reject</button>`:`<button class="btn btn-outline-warning" onclick="toggleUser('${u.id}','${u.status}')">${u.status==="Approved"?"Disable":"Enable"}</button>`}</div></td></tr>`).join("")}catch(e){toast(e.message)}}
window.approveUser=async id=>{try{await api("setUserStatus",{id,status:"Approved"});toast("User approved.");loadUsers();refreshBadge()}catch(e){toast(e.message)}}
window.rejectUser=async id=>{if(!confirm("Reject this registration?"))return;try{await api("setUserStatus",{id,status:"Rejected"});toast("Registration rejected.");loadUsers();refreshBadge()}catch(e){toast(e.message)}}
window.toggleUser=async(id,status)=>{try{await api("setUserStatus",{id,status:status==="Approved"?"Disabled":"Approved"});loadUsers()}catch(e){toast(e.message)}}
async function loadHistory(){try{const d=await api("history");history=d.history;$("#historyBody").innerHTML=history.map(h=>`<tr><td>${h.dateTime}</td><td>${h.user}</td><td>${h.unit}</td><td>${h.action}</td><td>${h.details}</td></tr>`).join("")}catch(e){toast(e.message)}}
$("#profileForm").onsubmit=async e=>{e.preventDefault();try{const d=await api("updateProfile",{name:$("#profileName").value,currentPassword:$("#currentPassword").value,newPassword:$("#newPassword").value});session=d.session;localStorage.setItem("pro4a_session",JSON.stringify(session));$("#loggedUser").textContent=`${session.name} • ${session.unit}`;$("#currentPassword").value=$("#newPassword").value="";toast("Profile updated.")}catch(e){toast(e.message)}}
(async()=>{const s=localStorage.getItem("pro4a_session");if(s){session=JSON.parse(s);await openApp()}})();